version: 2.1

orbs:
  yarn: artsy/yarn@dev:55f6486eeacc499426acd697242595df
  codecov: codecov/codecov@1.0.5
  auto: artsy/auto@1.0.1

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/relay:
          requires:
            - yarn/workflow-queue
      - yarn/lint:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
          important_files: src/setup_jest.ts .babelrc
          requires:
            - yarn/workflow-queue
          post-steps:
            - codecov/upload:
              file: coverage/lcov.info
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - yarn/lint
            - yarn/type-check
            - yarn/update-cache
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - yarn/lint
            - yarn/type-check
            - yarn/update-cache
