version: 2
jobs:
  relay:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn --check-files
      - run: yarn relay
  lint:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn --check-files
      - run: yarn lint 
  type-check:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn --check-files
      - run: yarn type-check
  deploy:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn --check-files
      - run: yarn semantic-release
      - run: cp .env.oss .env
      - run: yarn deploy-storybook
  test:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn --check-files
      - run: yarn test -w 4
  update-cache:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-deps-{{ checksum "yarn.lock" }}
        - yarn-deps-
    - run: yarn --check-files
    - save_cache:
        key: yarn-deps-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
workflows:
  version: 2
  build_and_verify:
    jobs:
      - update-cache
      - relay
      - lint
      - type-check
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - relay
            - lint
            - type-check
            - update-cache
