version: 2
jobs:
  relay:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn relay
  lint:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint 
  type-check:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn type-check
  deploy:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn semantic-release
      - run: cp .env.oss .env
      - run: yarn deploy-storybook
  test:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test --runInBand
  build:
    working_directory: ~/artsy/reaction
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
        - yarn-packages-
    - run: yarn --prefer-offline
    - save_cache:
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
        - ~/.cache/yarn
workflows:
  version: 2
  build_and_verify:
    jobs:
      - build
      - relay:
          requires:
            - build
      - lint:
          requires:
            - build
      - type-check:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test